# Generated by Django 3.2.4 on 2021-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_postimage_story_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='story',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
